---
kind: Service
apiVersion: v1
metadata:
  name: prices-service
  namespace: default
  labels:
    app: prices
spec:
  selector:
    app: prices
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
