---
kind: Service
apiVersion: v1
metadata:
  name: prices
  namespace: default
  labels:
    app: prices
spec:
  selector:
    app: prices
  ports:
    - name: tcp
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.168.100.200
